name: Bryan Shelton
markdown: redcarpet
pygments: true
permalink: pretty
exclude: [".gitignore", "CNAME", "LICENSE", "README.md", "Gruntfile.js", "package.json", "node_modules", "Gemfile*", "vendor"]
